spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  datasource:
    url: ${DB_URL} # mysql:3306/?? ??
    username: root
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver


springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
    path: /v3/api-docs
  default-consumes-media-type: application/json
  auto-tag-classes: true
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui.html

