spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  datasource:
    url: ${DB_URL} # mysql:3306/?? ??
    username: root
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver